// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/GameModeBase.h"
#include "B12_Test_LaurelennSgGameMode.generated.h"

/* ***** NOTE *****
 This code is generated by Unreal's TPS template
*/
class UCaptureGameDataAsset;
class UCaptureGameManager;

UCLASS(minimalapi)
class AB12_Test_LaurelennSgGameMode : public AGameModeBase
{
	GENERATED_BODY()

public:
	AB12_Test_LaurelennSgGameMode();

	UPROPERTY(Category = "#Setup", EditAnywhere, BlueprintReadWrite)
	UCaptureGameDataAsset* CaptureGameDataAsset;

	protected : 
	void BeginPlay() override;

	public : 
	UCaptureGameManager* GameManager;
};

