// Copyright Epic Games, Inc. All Rights Reserved.

#include "B12_Test_LaurelennSgGameMode.h"
#include "B12_Test_LaurelennSgCharacter.h"
#include "UObject/ConstructorHelpers.h"
#include "Managers/CaptureGameManager.h"

AB12_Test_LaurelennSgGameMode::AB12_Test_LaurelennSgGameMode()
{
	/* ***** NOTE *****
	This part belows is generated by Unreal's TPS Template,
	I deleted it because I think ClassFinder isn't a really good idea (if we change the name of the asset, or move it...)
	Event more in code directly (only programmers can edit it) ! I prefer create a childclass with a subclassOf reference (see BP_CaptureGameMode)
	***************** */

	/*set default pawn class to our Blueprinted character
	static ConstructorHelpers::FClassFinder<APawn> PlayerPawnBPClass(TEXT("/Game/X_UnrealTemplateContent/ThirdPerson/Blueprints/BP_ThirdPersonCharacter"));
	if (PlayerPawnBPClass.Class != NULL)
	{
		DefaultPawnClass = PlayerPawnBPClass.Class;
	}*/
}

void AB12_Test_LaurelennSgGameMode::BeginPlay()
{
	Super::BeginPlay();

	GameManager = GetGameInstance()->GetSubsystem<UCaptureGameManager>();
	if (GameManager)
	{
		GameManager->InitGameManager(CaptureGameDataAsset);
	}
	else
	{
		UE_LOG(LogTemp, Error, TEXT("B12_Test_LaurelennSgGameMode::BeginPlay : GameManager is null !"));
	}
}
